### ISSUE TITLE
error "Match data clobbered by buffer modification hooks"

### ISSUE THREAD

**Issue by gour** [syl20bnr/emacs-emoji-cheat-sheet-plus#5]
When I've the following in my init.el:

```
;; emoji cheat sheet
(use-package emoji-cheat-sheet-plus
  :ensure t
  :init
  (progn
    ;; enabled emoji in buffer
    (add-hook 'org-mode-hook 'emoji-cheat-sheet-plus-display-mode)
    ;; insert emoji with helm
    (global-set-key (kbd "C-c C-e") 'emoji-cheat-sheet-plus-insert)))
```

and trying to complete the following org-mode task:

```
** TODO test
   DEADLINE: <2016-11-13 Ned +1d>
   :PROPERTIES:
   :LAST_REPEAT: [2016-11-13 Ned 08:41]
   :END:
```

Emacs responds with:

```
Debugger entered--Lisp error: (error "Match data clobbered by buffer modification hooks")
  replace-match(#(" :LAST_REPEAT: [2016-11-13 Ned 08:41]" 0 3
(fontified nil) 3 4 (fontified nil) 4 15 (fontified nil) 15 16
(fontified nil) 17 39 (fontified nil)) t t)
  org--align-node-property()
  org-indent-line()
  org-entry-put(nil "LAST_REPEAT" "[2016-11-13 Ned 08:41]")
  org-auto-repeat-maybe("DONE")
```

The problem appears in new Emacs 25.1.x and after reporting about it in orgmode mailing list, the following suggestion was made in regard to emacs-emoji-cheat-sheet plus:

> It is probably missing `save-match-data' in function called through `after-change-functions' and
`post-command-hook'.

What do you think?

**Comment by d12frosted** [comment]
This is really annoying. Thanks to [mailing list](http://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00300.html) I've got the solution for this troubling issue that totally prevented me from using `org-mode`. Interesting that the problem exists only in Emacs 25+ and not in Emacs 24.5.1.

--- 

@gour Many thanks for finding the offending package. You saved me a lot of time.

--- 

Update: squashed my messages.

**Comment by d12frosted** [comment]
@gour Many thanks for the offending package. You saved me a lot of time.

**Comment by d12frosted** [comment]
Sorry, I meant, 'thanks for finding offending package'. And it saved me a lot of time, because I thought that it's something wrong with my configurations.

**Comment by johbo** [comment]
Just also got into this, was using scheduling and clocking in org and it got quite messed up. Disabling the emoji layer in my spacemacs configuration did solve it.

Thanks for reporting it!

**Comment by scarcella** [comment]
Would you be able to post a piece of code that can be added to my init.el?

**Comment by shivams** [comment]
The issue is still there. And it doesn't seem to be caused by `emoji` layer. I don't have `emoji` layer and yet the issue comes up.

**Comment by Anton-Latukha** [comment]
@shivams 
`"Match data clobbered by buffer modification hooks"` is a very often appearing issue. Your maybe just was not caused by the package.

But my - was caused by it.
I removed `emoji` layer, that so also removed this package, and `org--align-node-property:  match data clobbered by buffer modification hooks` went away.

**Comment by magthe** [comment]
Thank goodness for finding this ticket. Now my org-mode is usable again, and I can live without the _emoji_ layer.

**Comment by gorrog** [comment]
Removing the emoji layer and restarting spacemacs fixed this for me as well.
